In [1]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [2]:
!pip install -q transformers datasets accelerate sentence-transformers

In [1]:
import torch
import transformers

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)

Torch: 2.11.0+cu128
Transformers: 5.9.0

In [2]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

result = generator(
    "Artificial Intelligence is",
    max_new_tokens=30
)

print(result[0]["generated_text"])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=30) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Artificial Intelligence is a type of computer that can collect data from any computer, including any person.

In [4]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

model = AutoModel.from_pretrained(
    "bert-base-uncased"
)

text = "AI is transforming education"

inputs = tokenizer(
    text,
    return_tensors="pt"
)

with torch.no_grad():
    outputs = model(**inputs)

embedding = outputs.last_hidden_state.mean(dim=1)

print(embedding.shape)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

torch.Size([1, 768])

In [5]:
from transformers import pipeline

sentiment = pipeline(
    "sentiment-analysis"
)

print(
    sentiment(
        "This workshop was amazing!"
    )
)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9998730421066284}]

In [8]:
import transformers
print(transformers.__version__)

5.9.0

In [9]:
!pip uninstall -y transformers

Found existing installation: transformers 5.9.0
Uninstalling transformers-5.9.0:
  Successfully uninstalled transformers-5.9.0

In [10]:
!pip install -q transformers==4.44.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 40.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 25.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 56.2 MB/s eta 0:00:00

In [1]:
import transformers
print(transformers.__version__)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

4.44.2

In [2]:
import torch
import time
import psutil

from transformers import (
    pipeline,
    AutoTokenizer,
    AutoModel,
    AutoModelForCausalLM
)

print("=" * 60)
print("HUGGING FACE AI WORKSTATION")
print("=" * 60)

# ===================================================
# Device Information
# ===================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("\nDEVICE INFORMATION")
print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ===================================================
# Tokenization Demo
# ===================================================

print("\nTOKENIZATION")

bert_tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

text = """
Artificial Intelligence is transforming
education and cybersecurity.
"""

tokens = bert_tokenizer.tokenize(text)

print("Tokens:")
print(tokens)

print("Token Count:", len(tokens))

# ===================================================
# Embedding Demo
# ===================================================

print("\nEMBEDDINGS")

bert_model = AutoModel.from_pretrained(
    "bert-base-uncased"
).to(device)

inputs = bert_tokenizer(
    text,
    return_tensors="pt",
    padding=True,
    truncation=True
)

inputs = {
    k: v.to(device)
    for k, v in inputs.items()
}

with torch.no_grad():
    outputs = bert_model(**inputs)

embedding = outputs.last_hidden_state

print(
    "Embedding Shape:",
    embedding.shape
)

# Sentence embedding
sentence_embedding = embedding.mean(dim=1)

print(
    "Sentence Embedding Shape:",
    sentence_embedding.shape
)

# ===================================================
# Text Generation
# ===================================================

print("\nTEXT GENERATION")

generator = pipeline(
    "text-generation",
    model="distilgpt2",
    device=0 if torch.cuda.is_available() else -1
)

result = generator(
    "Machine Learning is",
    max_new_tokens=50,
    do_sample=True,
    temperature=0.8
)

print(
    result[0]["generated_text"]
)

# ===================================================
# Sentiment Analysis
# ===================================================

print("\nSENTIMENT ANALYSIS")

sentiment = pipeline(
    "sentiment-analysis",
    device=0 if torch.cuda.is_available() else -1
)

reviews = [
    "This workshop is amazing.",
    "The session was boring."
]

for review in reviews:
    print("\nReview:", review)
    print(sentiment(review))

# ===================================================
# Summarization
# ===================================================

print("\nSUMMARIZATION")

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
    device=0 if torch.cuda.is_available() else -1
)

article = """
Artificial Intelligence is a branch of computer science focused on creating
systems capable of performing tasks that typically require human intelligence.
These tasks include learning, reasoning, problem-solving, perception,
language understanding, and decision-making. AI technologies are being used
across industries such as healthcare, finance, cybersecurity, education,
and autonomous systems.
"""

summary = summarizer(
    article,
    max_length=40,
    min_length=10,
    do_sample=False
)

print(
    summary[0]["summary_text"]
)

# ===================================================
# Translation
# ===================================================

print("\nTRANSLATION")

translator = pipeline(
    "translation_en_to_fr",
    model="t5-small",
    device=0 if torch.cuda.is_available() else -1
)

translated = translator(
    "Artificial Intelligence is transforming education."
)

print(
    translated[0]["translation_text"]
)

# ===================================================
# Throughput Benchmark
# ===================================================

print("\nBENCHMARK")

prompt = "Explain Transformers in AI."

start = time.time()

output = generator(
    prompt,
    max_new_tokens=100
)

end = time.time()

generated_text = output[0]["generated_text"]

token_count = len(
    generator.tokenizer.encode(
        generated_text
    )
)

throughput = token_count / (end - start)

print(
    "Execution Time:",
    round(end - start, 2),
    "seconds"
)

print(
    "Tokens Generated:",
    token_count
)

print(
    "Tokens/sec:",
    round(throughput, 2)
)

# ===================================================
# Memory Monitoring
# ===================================================

print("\nMEMORY USAGE")

process = psutil.Process()

ram_usage = (
    process.memory_info().rss
    / 1024**2
)

print(
    "RAM Usage:",
    round(ram_usage, 2),
    "MB"
)

# ===================================================
# GPU Monitoring
# ===================================================

if torch.cuda.is_available():

    gpu_memory = (
        torch.cuda.memory_allocated()
        / 1024**3
    )

    print(
        "GPU Memory Used:",
        round(gpu_memory, 2),
        "GB"
    )

# ===================================================
# Completion
# ===================================================

print("\nExecution Complete")

============================================================
HUGGING FACE AI WORKSTATION
============================================================

DEVICE INFORMATION
Device: cuda
GPU: Tesla T4

TOKENIZATION

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Tokens:
['artificial', 'intelligence', 'is', 'transforming', 'education', 'and', 'cyber', '##se', '##cu', '##rity', '.']
Token Count: 11

EMBEDDINGS
Embedding Shape: torch.Size([1, 13, 768])
Sentence Embedding Shape: torch.Size([1, 768])

TEXT GENERATION

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

Machine Learning is an open-source project by the Association for the Advancement of Science (ASA) from the University of California, Berkeley.





The goal of ASA is to develop new tools for machine learning, but it has been

SENTIMENT ANALYSIS

Review: This workshop is amazing.
[{'label': 'POSITIVE', 'score': 0.999882698059082}]

Review: The session was boring.
[{'label': 'NEGATIVE', 'score': 0.9997355341911316}]

SUMMARIZATION

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Artificial Intelligence is a branch of computer science focused on creating systems capable of performing tasks that typically require human intelligence. These tasks include learning, reasoning, problem-solving, perception,

TRANSLATION

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Le renseignement artificiel transforme l'éducation.

BENCHMARK
Execution Time: 0.54 seconds
Tokens Generated: 97
Tokens/sec: 178.36

MEMORY USAGE
RAM Usage: 3627.11 MB
GPU Memory Used: 2.72 GB

Execution Complete

In [4]:
import peft
import torch

print("PEFT:", peft.__version__)
print("Torch:", torch.__version__)

PEFT: 0.19.1
Torch: 2.11.0+cu128

In [5]:
!pip uninstall -y torchao

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0

In [6]:
!pip install torchao>=0.16.0

In [1]:
import peft
import transformers
import torch

print(peft.__version__)
print(transformers.__version__)
print(torch.__version__)

0.19.1
4.44.2
2.11.0+cu128

In [3]:
# =====================================================
# LoRA Fine-Tuning Demo with DistilGPT2
# =====================================================

import os
os.environ["WANDB_DISABLED"] = "true"

import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)

from peft import (
    LoraConfig,
    get_peft_model,
    PeftModel
)

# =====================================================
# 1. Load Model & Tokenizer
# =====================================================

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    model_name
)

# =====================================================
# 2. Configure LoRA
# =====================================================

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(
    base_model,
    lora_config
)

print("\nTrainable Parameters")
model.print_trainable_parameters()

# =====================================================
# 3. Create Dataset
# =====================================================

texts = [
    "AI is transforming industries.",
    "Machine learning helps computers learn from data.",
    "LoRA enables efficient fine tuning of language models.",
    "Large language models generate human like text."
]

dataset = Dataset.from_dict(
    {"text": texts}
)

# =====================================================
# 4. Tokenization
# =====================================================

def tokenize_function(examples):

    result = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

    result["labels"] = result["input_ids"].copy()

    return result


tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

# =====================================================
# 5. Training Arguments
# =====================================================

training_args = TrainingArguments(
    output_dir="./lora_output",
    overwrite_output_dir=True,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    logging_steps=1,
    save_strategy="no",
    report_to="none"
)

# =====================================================
# 6. Trainer
# =====================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)

# =====================================================
# 7. Train
# =====================================================

print("\nStarting LoRA Training...\n")

trainer.train()

# =====================================================
# 8. Save Adapter
# =====================================================

adapter_path = "./lora_adapter"

model.save_pretrained(
    adapter_path
)

print("\nLoRA adapter saved!")

# =====================================================
# 9. Load Adapter Back
# =====================================================

base_model = AutoModelForCausalLM.from_pretrained(
    model_name
)

finetuned_model = PeftModel.from_pretrained(
    base_model,
    adapter_path
)

print("\nAdapter Loaded Successfully!")

# =====================================================
# 10. Test Generation
# =====================================================

prompt = "AI is"

inputs = tokenizer(
    prompt,
    return_tensors="pt"
)

with torch.no_grad():

    outputs = finetuned_model.generate(
        **inputs,
        max_new_tokens=30,
        do_sample=True,
        temperature=0.8
    )

generated_text = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("\nGenerated Text:")
print(generated_text)

print("\nLoRA Fine-Tuning Completed!")

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Trainable Parameters
trainable params: 147,456 || all params: 82,060,032 || trainable%: 0.1797

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

Starting LoRA Training...

LoRA adapter saved!

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Adapter Loaded Successfully!

Generated Text:
AI is now in a state of economic panic.























LoRA Fine-Tuning Completed!

In [5]:
# ==========================================================
# LoRA BENCHMARKING SCRIPT
# ==========================================================

import os
import time
import torch
import pandas as pd

os.environ["WANDB_DISABLED"] = "true"

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import (
    LoraConfig,
    get_peft_model
)

# ==========================================================
# DEVICE
# ==========================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("=" * 60)
print("LoRA Benchmark")
print("=" * 60)

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ==========================================================
# DATASET
# ==========================================================

texts = [
    "AI is transforming industries.",
    "Machine learning helps computers learn from data.",
    "LoRA enables efficient fine tuning of language models.",
    "Large language models generate human like text."
] * 250

dataset = Dataset.from_dict(
    {"text": texts}
)

# ==========================================================
# TOKENIZER
# ==========================================================

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

tokenizer.pad_token = tokenizer.eos_token

# ==========================================================
# TOKENIZATION
# ==========================================================

def tokenize_function(examples):

    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

    tokens["labels"] = tokens["input_ids"].copy()

    return tokens


tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# ==========================================================
# CONFIGURATIONS
# ==========================================================

configs = [
    {"r": 4, "alpha": 8},
    {"r": 8, "alpha": 16},
    {"r": 16, "alpha": 32},
    {"r": 32, "alpha": 64},
]

results = []

# ==========================================================
# BENCHMARK LOOP
# ==========================================================

for config in configs:

    r = config["r"]
    alpha = config["alpha"]

    print("\n" + "=" * 60)
    print(f"Testing Rank={r} Alpha={alpha}")
    print("=" * 60)

    # ------------------------------------------------------
    # Clear GPU Memory
    # ------------------------------------------------------

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    # ------------------------------------------------------
    # Load Model
    # ------------------------------------------------------

    base_model = AutoModelForCausalLM.from_pretrained(
        model_name
    )

    # ------------------------------------------------------
    # LoRA Config
    # ------------------------------------------------------

    lora_config = LoraConfig(
        r=r,
        lora_alpha=alpha,
        lora_dropout=0.1,
        bias="none",
        task_type="CAUSAL_LM"
    )

    model = get_peft_model(
        base_model,
        lora_config
    )

    model.to(device)

    # ------------------------------------------------------
    # Parameter Count
    # ------------------------------------------------------

    trainable_params = sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )

    total_params = sum(
        p.numel()
        for p in model.parameters()
    )

    print(f"Trainable Params: {trainable_params:,}")
    print(f"Total Params: {total_params:,}")

    # ------------------------------------------------------
    # Training Arguments
    # ------------------------------------------------------

    training_args = TrainingArguments(
        output_dir=f"./output_r{r}",
        overwrite_output_dir=True,
        num_train_epochs=2,
        per_device_train_batch_size=8,
        save_strategy="no",
        logging_steps=50,
        report_to="none"
    )

    # ------------------------------------------------------
    # Trainer
    # ------------------------------------------------------

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
        data_collator=data_collator
    )

    # ------------------------------------------------------
    # Train
    # ------------------------------------------------------

    start_time = time.time()

    train_output = trainer.train()

    training_time = time.time() - start_time

    final_loss = train_output.training_loss

    # ------------------------------------------------------
    # Peak GPU Memory
    # ------------------------------------------------------

    if torch.cuda.is_available():

        peak_gpu_memory = (
            torch.cuda.max_memory_allocated()
            / 1024**2
        )

    else:

        peak_gpu_memory = 0

    # ------------------------------------------------------
    # Generation Test
    # ------------------------------------------------------

    prompt = "AI is"

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    )

    inputs = {
        k: v.to(device)
        for k, v in inputs.items()
    }

    model.eval()

    with torch.no_grad():

        output = model.generate(
            **inputs,
            max_new_tokens=20,
            do_sample=True,
            temperature=0.8,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_text = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    # ------------------------------------------------------
    # Print Results
    # ------------------------------------------------------

    print("\nGenerated Text:")
    print(generated_text)

    print("\nTraining Time:",
          round(training_time, 2),
          "seconds")

    print("Peak GPU Memory:",
          round(peak_gpu_memory, 2),
          "MB")

    print("Final Loss:",
          round(final_loss, 4))

    # ------------------------------------------------------
    # Save Benchmark Result
    # ------------------------------------------------------

    results.append({
        "Rank": r,
        "Alpha": alpha,
        "Trainable_Params": trainable_params,
        "Training_Time_sec": round(training_time, 2),
        "Peak_GPU_MB": round(peak_gpu_memory, 2),
        "Final_Loss": round(final_loss, 4)
    })

# ==========================================================
# RESULTS TABLE
# ==========================================================

print("\n")
print("=" * 80)
print("FINAL BENCHMARK RESULTS")
print("=" * 80)

df = pd.DataFrame(results)

print(df)

# ==========================================================
# BEST CONFIG
# ==========================================================

best = df.sort_values(
    by="Final_Loss"
).iloc[0]

print("\nBest Configuration:")
print(best)

print("\nBenchmark Completed Successfully!")

============================================================
LoRA Benchmark
============================================================
Device: cuda
GPU: Tesla T4

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

============================================================
Testing Rank=4 Alpha=8
============================================================

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Trainable Params: 73,728
Total Params: 81,986,304

Generated Text:
AI is at the very core of the political movement. And it‡ is a political movement which has been

Training Time: 15.82 seconds
Peak GPU Memory: 1495.93 MB
Final Loss: 6.3744

============================================================
Testing Rank=8 Alpha=16
============================================================

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Trainable Params: 147,456
Total Params: 82,060,032

Generated Text:
AI is at the very core of the political movement. And it‡ is a political movement which has been

Training Time: 15.27 seconds
Peak GPU Memory: 1498.83 MB
Final Loss: 6.1109

============================================================
Testing Rank=16 Alpha=32
============================================================

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Trainable Params: 294,912
Total Params: 82,207,488

Generated Text:
AI is a popular, popular, and popular educational social networking platform, and is a popular, and popular educational

Training Time: 15.68 seconds
Peak GPU Memory: 1499.61 MB
Final Loss: 5.7135

============================================================
Testing Rank=32 Alpha=64
============================================================

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2504: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Trainable Params: 589,824
Total Params: 82,502,400

Generated Text:
AI is a popular engine. It offers the ability to create models, models and generate model models. The most

Training Time: 16.13 seconds
Peak GPU Memory: 1503.67 MB
Final Loss: 5.0696


================================================================================
FINAL BENCHMARK RESULTS
================================================================================
   Rank  Alpha  Trainable_Params  Training_Time_sec  Peak_GPU_MB  Final_Loss
0     4      8             73728              15.82      1495.93      6.3744
1     8     16            147456              15.27      1498.83      6.1109
2    16     32            294912              15.68      1499.61      5.7135
3    32     64            589824              16.13      1503.67      5.0696

Best Configuration:
Rank                     32.0000
Alpha                    64.0000
Trainable_Params     589824.0000
Training_Time_sec        16.1300
Peak_GPU_MB            1503.6700
Final_Loss                5.0696
Name: 3, dtype: float64

Benchmark Completed Successfully!